name: NPM Package

on:
    pull_request:
        paths-ignore:
            - '**.md'
    push:
        paths-ignore:
            - '**.md'

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node 20
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 20.x

            - name: Cache Node files
              uses: actions/cache@v4.0.2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: |
                      ~/.npm
                      ./transformer
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Update NPM
              run: npm install -g npm
            - name: Install dependencies
              run: npm ci
            - name: Run prettier
              run: npm run prettier
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node 20
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 20.x
            - name: Cache Node files
              uses: actions/cache@v4.0.2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: |
                      ~/.npm
                      ./transformer
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Update NPM
              run: npm install -g npm
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Run test
              run: npm run test
    publish:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        needs:
            - test
            - prettier
        steps:
            - uses: actions/checkout@v4
            - name: Setup node 20
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Cache Node files
              uses: actions/cache@v4.0.2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: |
                      ~/.npm
                      ./transformer
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Update NPM
              run: npm install -g npm
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Run publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
